-- sample_engagement.sql — DEMO data for the Workspace tabs. Clearly a sample.
-- Remove with:  DELETE FROM company.engagements WHERE id='ENG-001';
BEGIN;
INSERT INTO company.engagements (id,title,request_verbatim,mode,status,opened_by) VALUES ('ENG-001','Khôi phục mật khẩu tự phục vụ','Khách hàng bị khoá tài khoản cứ email cho support. Cho họ tự reset được không? Nhẹ, cần trước đợt gia hạn tháng 9.','micro','build','engagement-director') ON CONFLICT (id) DO NOTHING;
INSERT INTO company.sessions (external_id,engagement_id,label) VALUES ('smoke-eng001','ENG-001','Phiên build ENG-001') ON CONFLICT (external_id) DO NOTHING;
INSERT INTO company.tasks (id,engagement_id,requirement_id,title,detail,assignee,reporter,status,priority,attempt,blocked_by) VALUES ('T-101','ENG-001','R-042.1','Thiết kế schema RecoveryToken (token dùng 1 lần, TTL 15p)','Bảng RecoveryToken: token băm (không lưu plaintext), user_id, expires_at (now()+15p), used_at nullable. Ràng buộc: 1 token sống / user; phát cái mới thì vô hiệu cái cũ.','engineering-backend-architect','project-manager-senior','accepted','high',1,NULL),('T-102','ENG-001','R-042.1','Endpoint phát hành token khôi phục','POST /recovery: nhận email → phát token, gửi mail. Chống enumeration ở T-104. Cần log timing + enumeration để QA kiểm.','engineering-backend-architect','project-manager-senior','in_qa','high',1,NULL),('T-103','ENG-001','R-042.1','Màn hình nhập email + màn hình đặt lại mật khẩu','2 màn: (1) nhập email yêu cầu reset, (2) redeem token + đặt mật khẩu mới. Copy nút đang chờ PO chốt.','engineering-frontend-developer','project-manager-senior','in_progress','medium',0,NULL),('T-104','ENG-001','R-042.2','Chống lộ email chưa đăng ký (đồng nhất response + timing)','Email tồn tại hay không đều trả cùng response và cùng timing. Đang chặn bởi A2 (support xem timestamp hay chỉ số lần?) — cần owner quyết.','engineering-backend-architect','project-manager-senior','todo','high',0,'A2'),('T-105','ENG-001','R-042.1','Rate-limit: request thứ 2 trong 60s trả token cũ','Trong 60s kể từ token gần nhất, request mới phải trả LẠI token cũ (không tạo token thứ hai). QA fail 2 lần: cooldown chưa chặn.','engineering-backend-architect','project-manager-senior','rejected','urgent',2,NULL),('T-106','ENG-001','R-042.3','Gửi SMS song song với email','Kênh SMS song song email khi khôi phục. Hoãn: ngoài phạm vi đợt gia hạn tháng 9, chờ owner xếp lại ưu tiên.','engineering-frontend-developer','project-manager-senior','deferred','low',0,NULL) ON CONFLICT (id) DO NOTHING;
INSERT INTO company.messages (engagement_id,task_id,from_agent,to_agent,kind,body,idempotency_key) VALUES ('ENG-001',NULL,'engagement-director','product-business-analyst','handoff','ENG-001 đã mở. Yêu cầu: khách tự khôi phục mật khẩu, không qua support. Hạn 2026-09-01. Sizing Micro.','e1-m1'),('ENG-001',NULL,'product-business-analyst','product-owner','handoff','SPEC-042 xong: 3 requirement, 5 edge case. Ambiguity register còn A1 (token sống bao lâu) và A2 (support xem timestamp hay chỉ đếm số lần?).','e1-m2'),('ENG-001',NULL,'product-owner','engagement-director','ruling','A1: chốt 15 phút cho khớp luồng SSO hiện có. A2 phải hỏi khách — không tự quyết được.','e1-m3'),('ENG-001','T-101','project-manager-senior','engineering-backend-architect','handoff','Backlog xếp theo RICE: T-101..T-102,T-104,T-105 → backend; T-103,T-106 → frontend. Bắt đầu T-101.','e1-m4'),('ENG-001','T-102','engineering-backend-architect','testing-evidence-collector','handoff','T-102 xong, mời QA. Bằng chứng ở company/evidence/T-102/ (timing.log, enumeration.log).','e1-m5'),('ENG-001','T-105','testing-evidence-collector','engineering-backend-architect','qa_verdict','T-105 FAIL lần 2/3: cooldown chưa chặn request thứ 2 trong 60s, tạo token thứ hai. Xem repeat.log. Chỉ cần sửa đúng tiêu chí này.','e1-m6'),('ENG-001','T-103','engineering-frontend-developer','product-owner','chat','T-103 đang làm. Nút trên màn hình redeem nên ghi ''Đặt lại mật khẩu'' hay ''Xác nhận''? Cần chốt copy.','e1-m7'),('ENG-001','T-104','engagement-director',NULL,'escalation','Cần CEO/CTO quyết A2: support được xem *thời điểm* các lần thử reset, hay chỉ *số lần*? Đang chặn T-104.','e1-m8') ON CONFLICT (idempotency_key) DO NOTHING;
-- A few sample reactions (agents ack each other), keyed off message idempotency keys.
INSERT INTO company.message_reactions (message_id, agent, emoji)
SELECT m.id, v.agent, v.emoji FROM (VALUES
  ('e1-m2','product-owner','👍'),
  ('e1-m2','engagement-director','👍'),
  ('e1-m2','project-manager-senior','👍'),
  ('e1-m3','engagement-director','✅'),
  ('e1-m5','testing-evidence-collector','👀'),
  ('e1-m6','engineering-backend-architect','🔧'),
  ('e1-m6','engineering-frontend-developer','🔧')
) v(k, agent, emoji)
JOIN company.messages m ON m.idempotency_key = v.k
ON CONFLICT DO NOTHING;
COMMIT;
